-- Local fire module baseline for Huixiaobao (dev_manager)
-- CREATE TABLE IF NOT EXISTS; InnoDB utf8mb4; pragmatic for local boot

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `fire_company` (
  `company_id` bigint NOT NULL AUTO_INCREMENT,
  `company_code` varchar(64) DEFAULT NULL,
  `company_name` varchar(200) NOT NULL DEFAULT '',
  `is_key_unit` char(1) DEFAULT '0',
  `short_name` varchar(100) DEFAULT NULL,
  `company_type` varchar(50) DEFAULT NULL,
  `building_type` varchar(50) DEFAULT NULL,
  `total_land_area` decimal(12,2) DEFAULT NULL,
  `total_building_area` decimal(12,2) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `province` varchar(50) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `district` varchar(50) DEFAULT NULL,
  `check_in_longitude` double DEFAULT NULL,
  `check_in_latitude` double DEFAULT NULL,
  `check_in_radius` int DEFAULT NULL,
  `check_in_address` varchar(500) DEFAULT NULL,
  `contact_person` varchar(64) DEFAULT NULL,
  `contact_phone` varchar(32) DEFAULT NULL,
  `contact_email` varchar(100) DEFAULT NULL,
  `contract_start_date` date DEFAULT NULL,
  `contract_end_date` date DEFAULT NULL,
  `contract_status` char(1) DEFAULT '0',
  `contract_id` bigint DEFAULT NULL,
  `project_name` varchar(200) DEFAULT NULL,
  `contract_name` varchar(200) DEFAULT NULL,
  `entry_unit` varchar(100) DEFAULT NULL,
  `sign_requirement` char(1) DEFAULT '0',
  `credit_code` varchar(50) DEFAULT NULL,
  `auto_fire_system` char(1) DEFAULT '1',
  `building_floor_count` int DEFAULT NULL,
  `building_height` decimal(10,2) DEFAULT NULL,
  `maintenance_standard` varchar(255) DEFAULT NULL,
  `maintenance_content` varchar(1000) DEFAULT NULL,
  `project_overview` varchar(1000) DEFAULT NULL,
  `report_mode` char(1) DEFAULT '0',
  `project_leader_name` varchar(50) DEFAULT NULL,
  `technical_leader_name` varchar(50) DEFAULT NULL,
  `property_manage_unit` varchar(200) DEFAULT NULL,
  `maintenance_scheme_name` varchar(255) DEFAULT NULL,
  `maintenance_scheme_path` varchar(500) DEFAULT NULL,
  `building_count` int DEFAULT NULL,
  `equipment_count` int DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`company_id`),
  KEY `idx_fire_company_name` (`company_name`),
  KEY `idx_fire_company_del` (`del_flag`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fire company/customer';

CREATE TABLE IF NOT EXISTS `fire_user_company` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `role_type` varchar(32) DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fuc_user` (`user_id`),
  KEY `idx_fuc_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='user-company bind';

CREATE TABLE IF NOT EXISTS `fire_building` (
  `building_id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `building_code` varchar(64) DEFAULT NULL,
  `building_name` varchar(200) NOT NULL DEFAULT '',
  `building_type` varchar(64) DEFAULT NULL,
  `auto_fire_system` char(1) DEFAULT '1',
  `address` varchar(500) DEFAULT NULL,
  `land_area` decimal(12,2) DEFAULT NULL,
  `area` decimal(12,2) DEFAULT NULL,
  `floor_count` int DEFAULT NULL,
  `building_height` decimal(10,2) DEFAULT NULL,
  `above_ground_floors` int DEFAULT NULL,
  `underground_floors` int DEFAULT NULL,
  `emergency_exits` int DEFAULT NULL,
  `evacuation_stairs` int DEFAULT NULL,
  `fire_elevators` int DEFAULT NULL,
  `refuge_floor` varchar(100) DEFAULT NULL,
  `fire_level` varchar(32) DEFAULT NULL,
  `contact_person` varchar(64) DEFAULT NULL,
  `contact_phone` varchar(32) DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`building_id`),
  KEY `idx_fire_building_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fire building';

CREATE TABLE IF NOT EXISTS `fire_equipment` (
  `equipment_id` bigint NOT NULL AUTO_INCREMENT,
  `equipment_code` varchar(64) DEFAULT NULL,
  `equipment_name` varchar(200) NOT NULL DEFAULT '',
  `equipment_type` varchar(64) DEFAULT NULL,
  `building_id` bigint DEFAULT NULL,
  `building_name` varchar(200) DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `floor_no` varchar(50) DEFAULT NULL,
  `system_type_id` bigint DEFAULT NULL,
  `system_name` varchar(200) DEFAULT NULL,
  `project_category` varchar(200) DEFAULT NULL,
  `location` varchar(500) DEFAULT NULL,
  `manufacturer` varchar(200) DEFAULT NULL,
  `model` varchar(100) DEFAULT NULL,
  `quantity` int DEFAULT 1,
  `image` varchar(500) DEFAULT NULL,
  `production_date` date DEFAULT NULL,
  `install_date` date DEFAULT NULL,
  `expire_date` date DEFAULT NULL,
  `last_check_date` date DEFAULT NULL,
  `next_check_date` date DEFAULT NULL,
  `equipment_status` char(1) DEFAULT '0',
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`equipment_id`),
  KEY `idx_fire_equip_company` (`company_id`),
  KEY `idx_fire_equip_building` (`building_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fire equipment';

CREATE TABLE IF NOT EXISTS `fire_system_type` (
  `type_id` bigint NOT NULL AUTO_INCREMENT,
  `type_code` varchar(64) DEFAULT NULL,
  `type_name` varchar(100) NOT NULL DEFAULT '',
  `parent_id` bigint DEFAULT 0,
  `order_num` int DEFAULT 0,
  `icon` varchar(100) DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fire system type';

CREATE TABLE IF NOT EXISTS `fire_maintenance_template` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `level` int DEFAULT NULL,
  `parent_id` bigint DEFAULT 0,
  `item_name` varchar(200) NOT NULL DEFAULT '',
  `item_code` varchar(64) DEFAULT NULL,
  `sort_order` int DEFAULT 0,
  `template_type` char(1) DEFAULT '0',
  `remark` varchar(500) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fmt_parent` (`parent_id`),
  KEY `idx_fmt_type` (`template_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='maintenance template';

CREATE TABLE IF NOT EXISTS `fire_maintenance_task` (
  `task_id` bigint NOT NULL AUTO_INCREMENT,
  `task_name` varchar(200) DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `plan_start_time` datetime DEFAULT NULL,
  `plan_end_time` datetime DEFAULT NULL,
  `actual_start_time` datetime DEFAULT NULL,
  `actual_end_time` datetime DEFAULT NULL,
  `task_status` char(1) DEFAULT '0',
  `total_items` int DEFAULT 0,
  `completed_items` int DEFAULT 0,
  `normal_items` int DEFAULT 0,
  `fault_items` int DEFAULT 0,
  `no_device_items` int DEFAULT 0,
  `executor_id` bigint DEFAULT NULL,
  `executor_name` varchar(64) DEFAULT NULL,
  `task_type` char(1) DEFAULT '0',
  `period_type` char(1) DEFAULT NULL,
  `period_year` int DEFAULT NULL,
  `period_num` int DEFAULT NULL,
  `manager_id` bigint DEFAULT NULL,
  `manager_name` varchar(64) DEFAULT NULL,
  `manager_phone` varchar(32) DEFAULT NULL,
  `operator_ids` varchar(500) DEFAULT NULL,
  `operator_names` varchar(500) DEFAULT NULL,
  `building_id` bigint DEFAULT NULL,
  `building_name` varchar(200) DEFAULT NULL,
  `selected_system_ids` varchar(500) DEFAULT NULL,
  `selected_fire_test_ids` varchar(500) DEFAULT NULL,
  `maintenance_summary` text,
  `maintenance_time` date DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  KEY `idx_fmtask_company` (`company_id`),
  KEY `idx_fmtask_status` (`task_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='maintenance task';

CREATE TABLE IF NOT EXISTS `fire_maintenance_record` (
  `record_id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint DEFAULT NULL,
  `template_id` bigint DEFAULT NULL,
  `level` int DEFAULT NULL,
  `parent_record_id` bigint DEFAULT NULL,
  `item_name` varchar(200) DEFAULT NULL,
  `item_code` varchar(64) DEFAULT NULL,
  `check_result` char(1) DEFAULT '0',
  `fault_description` varchar(1000) DEFAULT NULL,
  `fault_images` varchar(1000) DEFAULT NULL,
  `repair_suggestion` varchar(1000) DEFAULT NULL,
  `other_notes` varchar(1000) DEFAULT NULL,
  `device_location` varchar(200) DEFAULT NULL,
  `test_situation` varchar(500) DEFAULT NULL,
  `test_time` datetime DEFAULT NULL,
  `test_result` varchar(500) DEFAULT NULL,
  `site_photos` varchar(1000) DEFAULT NULL,
  `check_time` datetime DEFAULT NULL,
  `checker_id` bigint DEFAULT NULL,
  `checker_name` varchar(64) DEFAULT NULL,
  `sort_order` int DEFAULT 0,
  `record_type` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`record_id`),
  KEY `idx_fmrec_task` (`task_id`),
  KEY `idx_fmrec_parent` (`parent_record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='maintenance record';

CREATE TABLE IF NOT EXISTS `fire_inspection` (
  `inspection_id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `inspection_type` char(1) DEFAULT '0',
  `building_id` bigint DEFAULT NULL,
  `building_name` varchar(200) DEFAULT NULL,
  `floor` varchar(50) DEFAULT NULL,
  `system_type` varchar(64) DEFAULT NULL,
  `system_name` varchar(200) DEFAULT NULL,
  `equipment_name` varchar(200) DEFAULT NULL,
  `equipment_count` int DEFAULT NULL,
  `location` varchar(500) DEFAULT NULL,
  `inspection_time` datetime DEFAULT NULL,
  `equipment_status` char(1) DEFAULT '0',
  `inspector_id` bigint DEFAULT NULL,
  `inspector_name` varchar(64) DEFAULT NULL,
  `image_urls` varchar(2000) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `task_name` varchar(200) DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`inspection_id`),
  KEY `idx_fi_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fire inspection';

CREATE TABLE IF NOT EXISTS `fire_inspection_session` (
  `session_id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint DEFAULT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `check_in_time` datetime DEFAULT NULL,
  `check_in_longitude` double DEFAULT NULL,
  `check_in_latitude` double DEFAULT NULL,
  `check_in_address` varchar(500) DEFAULT NULL,
  `check_in_remark` varchar(500) DEFAULT NULL,
  `check_out_time` datetime DEFAULT NULL,
  `check_out_longitude` double DEFAULT NULL,
  `check_out_latitude` double DEFAULT NULL,
  `check_out_address` varchar(500) DEFAULT NULL,
  `check_out_remark` varchar(500) DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `session_date` date DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`session_id`),
  KEY `idx_fis_user_date` (`user_id`, `session_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='inspection session';

CREATE TABLE IF NOT EXISTS `fire_fault_repair` (
  `repair_id` bigint NOT NULL AUTO_INCREMENT,
  `repair_no` varchar(64) DEFAULT NULL,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `system_type_id` bigint DEFAULT NULL,
  `system_type_name` varchar(200) DEFAULT NULL,
  `equipment_id` bigint DEFAULT NULL,
  `equipment_name` varchar(200) DEFAULT NULL,
  `found_time` datetime DEFAULT NULL,
  `is_reported` char(1) DEFAULT '0',
  `urgency_level` char(1) DEFAULT '0',
  `fault_description` varchar(1000) DEFAULT NULL,
  `fault_images` varchar(1000) DEFAULT NULL,
  `reporter_name` varchar(64) DEFAULT NULL,
  `reporter_id` bigint DEFAULT NULL,
  `reporter_phone` varchar(32) DEFAULT NULL,
  `customer_address` varchar(500) DEFAULT NULL,
  `repair_status` char(1) DEFAULT '0',
  `repair_user_id` bigint DEFAULT NULL,
  `repair_person` varchar(64) DEFAULT NULL,
  `repair_phone` varchar(32) DEFAULT NULL,
  `dispatch_by` varchar(64) DEFAULT NULL,
  `dispatch_time` datetime DEFAULT NULL,
  `accept_time` datetime DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `complete_time` datetime DEFAULT NULL,
  `repair_description` varchar(1000) DEFAULT NULL,
  `repair_images` varchar(1000) DEFAULT NULL,
  `status` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`repair_id`),
  KEY `idx_fire_fault_repair_reporter_id` (`reporter_id`),
  KEY `idx_fire_fault_repair_repair_user_id` (`repair_user_id`),
  KEY `idx_fire_fault_repair_company_status` (`company_id`, `repair_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='fault repair';

CREATE TABLE IF NOT EXISTS `fire_check_in` (
  `check_in_id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint DEFAULT NULL,
  `company_name` varchar(200) DEFAULT NULL,
  `task_id` bigint DEFAULT NULL,
  `task_name` varchar(200) DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `user_name` varchar(64) DEFAULT NULL,
  `check_in_time` datetime DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `check_in_type` char(1) DEFAULT '0',
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`check_in_id`),
  KEY `idx_fci_company` (`company_id`),
  KEY `idx_fci_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='check in';

CREATE TABLE IF NOT EXISTS `fire_check_in_image` (
  `image_id` bigint NOT NULL AUTO_INCREMENT,
  `check_in_id` bigint NOT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `image_name` varchar(200) DEFAULT NULL,
  `sort_order` int DEFAULT 0,
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  KEY `idx_fcii_checkin` (`check_in_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='check in image';

CREATE TABLE IF NOT EXISTS `fire_report_record` (
  `report_id` bigint NOT NULL AUTO_INCREMENT,
  `task_id` bigint DEFAULT NULL,
  `task_name` varchar(200) DEFAULT NULL,
  `report_name` varchar(200) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_size` bigint DEFAULT NULL,
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`report_id`),
  KEY `idx_frr_task` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='report record';

CREATE TABLE IF NOT EXISTS `fire_contract` (
  `contract_id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `company_name` varchar(200) DEFAULT '',
  `project_name` varchar(200) DEFAULT '',
  `contract_name` varchar(200) NOT NULL,
  `contract_no` varchar(100) NOT NULL,
  `contract_amount` decimal(12,2) DEFAULT 0.00,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `entry_unit` varchar(100) DEFAULT '',
  `attachment_name` varchar(255) DEFAULT '',
  `attachment_path` varchar(500) DEFAULT '',
  `terminate_flag` char(1) DEFAULT '0',
  `terminate_time` datetime DEFAULT NULL,
  `renewed_from_id` bigint DEFAULT NULL,
  `del_flag` char(1) DEFAULT '0',
  `create_by` varchar(64) DEFAULT '',
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) DEFAULT '',
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`contract_id`),
  KEY `idx_fire_contract_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='maintenance contract';

INSERT INTO `fire_company` (`company_id`, `company_name`, `status`, `del_flag`, `create_by`, `create_time`, `remark`)
SELECT 1, 'Demo Company', '0', '0', 'admin', NOW(), 'local baseline sample'
WHERE NOT EXISTS (SELECT 1 FROM `fire_company` WHERE `company_id` = 1);

SET FOREIGN_KEY_CHECKS = 1;
