-- Phase3 org rbac
SET NAMES utf8mb4;
SET @OLD_FK := @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;
DROP TABLE IF EXISTS bak_p3_sys_dept;
CREATE TABLE bak_p3_sys_dept AS SELECT * FROM sys_dept;
DROP TABLE IF EXISTS bak_p3_sys_role;
CREATE TABLE bak_p3_sys_role AS SELECT * FROM sys_role;
DROP TABLE IF EXISTS bak_p3_sys_post;
CREATE TABLE bak_p3_sys_post AS SELECT * FROM sys_post;
DROP TABLE IF EXISTS bak_p3_sys_user;
CREATE TABLE bak_p3_sys_user AS SELECT * FROM sys_user;
DROP TABLE IF EXISTS bak_p3_sys_user_role;
CREATE TABLE bak_p3_sys_user_role AS SELECT * FROM sys_user_role;
DROP TABLE IF EXISTS bak_p3_sys_user_post;
CREATE TABLE bak_p3_sys_user_post AS SELECT * FROM sys_user_post;
DROP TABLE IF EXISTS bak_p3_sys_role_menu;
CREATE TABLE bak_p3_sys_role_menu AS SELECT * FROM sys_role_menu;
DROP TABLE IF EXISTS bak_p3_sys_role_dept;
CREATE TABLE bak_p3_sys_role_dept AS SELECT * FROM sys_role_dept;
UPDATE sys_dept SET dept_name='中汇三江（广东）消防科技有限公司', parent_id=0, ancestors='0', order_num=0, status='0', del_flag='0', update_by='admin', update_time=NOW() WHERE dept_id=100;
UPDATE sys_dept SET dept_name='维保部', parent_id=100, ancestors='0,100', order_num=10, status='0', del_flag='0', update_by='admin', update_time=NOW() WHERE dept_id=110;
INSERT INTO sys_dept (dept_id,parent_id,ancestors,dept_name,order_num,status,del_flag,create_by,create_time) SELECT 110,100,'0,100','维保部',10,'0','0','admin',NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE dept_id=110);
SET @other_dept := (SELECT dept_id FROM sys_dept WHERE dept_name='其他公司' AND parent_id=0 LIMIT 1);
INSERT INTO sys_dept (parent_id,ancestors,dept_name,order_num,status,del_flag,create_by,create_time) SELECT 0,'0','其他公司',90,'0','0','admin',NOW() FROM DUAL WHERE @other_dept IS NULL;
UPDATE sys_dept SET status='1', del_flag='2', update_by='admin', update_time=NOW() WHERE dept_id IN (101,102,103,104,105,106,107,108,109,111,112,113) AND dept_id NOT IN (100,110);
UPDATE sys_role SET role_name='超级管理员', role_sort=1, data_scope='1', status='0', del_flag='0', update_by='admin', update_time=NOW() WHERE role_key='admin';
UPDATE sys_role SET role_name='项目负责人', role_sort=2, data_scope='1', status='0', del_flag='0', remark='phase3 PM all data', update_by='admin', update_time=NOW() WHERE role_key='project_manager';
UPDATE sys_role SET role_name='维保组长', role_sort=3, data_scope='5', status='0', del_flag='0', update_by='admin', update_time=NOW() WHERE role_key='team_leader';
UPDATE sys_role SET role_key='maintenance_member', role_name='维保组员', role_sort=4, data_scope='5', status='0', del_flag='0', remark='phase3 was fire_operator', update_by='admin', update_time=NOW() WHERE role_key='fire_operator' AND del_flag='0';
INSERT INTO sys_role (role_name,role_key,role_sort,data_scope,status,del_flag,create_by,create_time,remark) SELECT '维保组员','maintenance_member',4,'5','0','0','admin',NOW(),'phase3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_role WHERE role_key='maintenance_member' AND del_flag='0');
INSERT INTO sys_role_menu (role_id,menu_id) SELECT r.role_id,2000 FROM sys_role r WHERE r.role_key IN ('project_manager','team_leader','maintenance_member') AND r.del_flag='0' AND EXISTS (SELECT 1 FROM sys_menu m WHERE m.menu_id=2000) AND NOT EXISTS (SELECT 1 FROM sys_role_menu rm WHERE rm.role_id=r.role_id AND rm.menu_id=2000);
INSERT INTO sys_role_menu (role_id,menu_id) SELECT r.role_id,m.menu_id FROM sys_role r CROSS JOIN sys_menu m WHERE r.role_key='maintenance_member' AND r.del_flag='0' AND m.perms IN ('fire:task:view','fire:task:list','fire:task:query','fire:task:detail','fire:report:view','fire:report:list','fire:repair:view','fire:repair:list','fire:checkIn:view','fire:checkIn:list') AND IFNULL(m.visible,'0')='0' AND NOT EXISTS (SELECT 1 FROM sys_role_menu rm WHERE rm.role_id=r.role_id AND rm.menu_id=m.menu_id);
DELETE rm FROM sys_role_menu rm INNER JOIN sys_role r ON r.role_id=rm.role_id INNER JOIN sys_menu m ON m.menu_id=rm.menu_id WHERE r.role_key='project_manager' AND (m.perms LIKE 'system:role%' OR m.perms LIKE 'system:menu%' OR m.perms LIKE 'system:dept%' OR m.perms LIKE 'system:dict%' OR m.perms LIKE 'system:config%' OR m.perms LIKE 'system:notice%' OR m.perms LIKE 'monitor:%' OR m.perms LIKE 'tool:%' OR m.url IN ('/system/role','/system/menu','/system/dept','/system/dict','/system/config'));
UPDATE sys_role SET status='1', del_flag='2', update_by='admin', update_time=NOW(), remark=CONCAT(IFNULL(remark,''),' | phase3 disabled') WHERE role_key IN ('common','fire_dept_admin','dept_staff','auditor','fire_operator');
INSERT INTO sys_post (post_code,post_name,post_sort,status,create_by,create_time,remark) SELECT 'PROJECT_MANAGER','项目负责人',1,'0','admin',NOW(),'phase3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE post_code='PROJECT_MANAGER');
INSERT INTO sys_post (post_code,post_name,post_sort,status,create_by,create_time,remark) SELECT 'MAINTENANCE_LEADER','维保组长',2,'0','admin',NOW(),'phase3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE post_code='MAINTENANCE_LEADER');
INSERT INTO sys_post (post_code,post_name,post_sort,status,create_by,create_time,remark) SELECT 'MAINTENANCE_MEMBER','维保组员',3,'0','admin',NOW(),'phase3' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM sys_post WHERE post_code='MAINTENANCE_MEMBER');
UPDATE sys_post SET post_name='项目负责人', post_sort=1, status='0' WHERE post_code='PROJECT_MANAGER';
UPDATE sys_post SET post_name='维保组长', post_sort=2, status='0' WHERE post_code='MAINTENANCE_LEADER';
UPDATE sys_post SET post_name='维保组员', post_sort=3, status='0' WHERE post_code='MAINTENANCE_MEMBER';
UPDATE sys_post SET status='1', remark=CONCAT(IFNULL(remark,''),' | phase3 disabled') WHERE post_code NOT IN ('PROJECT_MANAGER','MAINTENANCE_LEADER','MAINTENANCE_MEMBER');
SET @post_pm := (SELECT post_id FROM sys_post WHERE post_code='PROJECT_MANAGER' LIMIT 1);
SET @post_tl := (SELECT post_id FROM sys_post WHERE post_code='MAINTENANCE_LEADER' LIMIT 1);
SET @post_mm := (SELECT post_id FROM sys_post WHERE post_code='MAINTENANCE_MEMBER' LIMIT 1);
SET @role_pm := (SELECT role_id FROM sys_role WHERE role_key='project_manager' AND del_flag='0' LIMIT 1);
SET @role_tl := (SELECT role_id FROM sys_role WHERE role_key='team_leader' AND del_flag='0' LIMIT 1);
SET @role_mm := (SELECT role_id FROM sys_role WHERE role_key='maintenance_member' AND del_flag='0' LIMIT 1);
SET @role_admin := (SELECT role_id FROM sys_role WHERE role_key='admin' AND del_flag='0' LIMIT 1);
UPDATE sys_user SET dept_id=100, status='0', del_flag='0', allow_admin_login='1', allow_mini_login='1', audit_status='0', remark='phase3 admin root', update_by='admin', update_time=NOW() WHERE user_id=1;
DELETE FROM sys_user_role WHERE user_id=1;
INSERT INTO sys_user_role (user_id,role_id) SELECT 1,@role_admin FROM DUAL WHERE @role_admin IS NOT NULL;
DELETE FROM sys_user_post WHERE user_id=1;
UPDATE sys_user SET status='1', allow_admin_login='0', allow_mini_login='0', remark='phase3 disabled demo', update_by='admin', update_time=NOW() WHERE user_id=5 AND login_name='mouchao';
DELETE FROM sys_user_role WHERE user_id=5;
DELETE FROM sys_user_post WHERE user_id=5;
UPDATE sys_user SET dept_id=110, status='0', del_flag='0', allow_admin_login='1', allow_mini_login='1', audit_status='0', remark='phase3 project_manager', update_by='admin', update_time=NOW() WHERE user_id=7 AND login_name='18782959011';
DELETE FROM sys_user_role WHERE user_id=7;
INSERT INTO sys_user_role (user_id,role_id) SELECT 7,@role_pm FROM DUAL WHERE @role_pm IS NOT NULL;
DELETE FROM sys_user_post WHERE user_id=7;
INSERT INTO sys_user_post (user_id,post_id) SELECT 7,@post_pm FROM DUAL WHERE @post_pm IS NOT NULL;
UPDATE sys_user SET dept_id=110, status='0', del_flag='0', allow_admin_login='0', allow_mini_login='1', remark='phase3 MANUAL_CONFIRM no auto PM', update_by='admin', update_time=NOW() WHERE user_id=14 AND del_flag='0';
DELETE FROM sys_user_role WHERE user_id=14;
DELETE FROM sys_user_post WHERE user_id=14;
UPDATE sys_user SET dept_id=110, status='0', del_flag='0', allow_admin_login='1', allow_mini_login='1', audit_status='0', remark='phase3 team_leader', update_by='admin', update_time=NOW() WHERE user_id=17 AND login_name='YY';
DELETE FROM sys_user_role WHERE user_id=17;
INSERT INTO sys_user_role (user_id,role_id) SELECT 17,@role_tl FROM DUAL WHERE @role_tl IS NOT NULL;
DELETE FROM sys_user_post WHERE user_id=17;
INSERT INTO sys_user_post (user_id,post_id) SELECT 17,@post_tl FROM DUAL WHERE @post_tl IS NOT NULL;
UPDATE sys_user SET dept_id=110, user_name=login_name, status='0', del_flag='0', allow_admin_login='1', allow_mini_login='1', audit_status='0', remark='phase3 maintenance_member', update_by='admin', update_time=NOW() WHERE user_id=16 AND login_name='13413462481';
DELETE FROM sys_user_role WHERE user_id=16;
INSERT INTO sys_user_role (user_id,role_id) SELECT 16,@role_mm FROM DUAL WHERE @role_mm IS NOT NULL;
DELETE FROM sys_user_post WHERE user_id=16;
INSERT INTO sys_user_post (user_id,post_id) SELECT 16,@post_mm FROM DUAL WHERE @post_mm IS NOT NULL;
UPDATE sys_user SET allow_admin_login='0', remark='phase3 MANUAL_CONFIRM identity', update_by='admin', update_time=NOW() WHERE user_id IN (6,8,9,11) AND del_flag='0';
DELETE ur FROM sys_user_role ur WHERE ur.user_id IN (6,8,9,11);
UPDATE sys_user SET status='1', allow_admin_login='0', allow_mini_login='0', remark='phase3 MANUAL_CONFIRM disabled', update_by='admin', update_time=NOW() WHERE user_id IN (10,12,13) AND del_flag='0';
DELETE ur FROM sys_user_role ur WHERE ur.user_id IN (10,12,13);
DELETE up FROM sys_user_post up WHERE up.user_id IN (10,12,13);
DELETE ur FROM sys_user_role ur INNER JOIN sys_role r ON r.role_id=ur.role_id WHERE r.del_flag='2' OR r.role_key IN ('common','fire_dept_admin','dept_staff','auditor','fire_operator');
DELETE up FROM sys_user_post up INNER JOIN sys_post p ON p.post_id=up.post_id WHERE p.status='1' AND p.post_code NOT IN ('PROJECT_MANAGER','MAINTENANCE_LEADER','MAINTENANCE_MEMBER');
UPDATE sys_user SET dept_id=100 WHERE user_id=1;
UPDATE sys_user SET dept_id=110 WHERE user_id IN (7,14,16,17) AND del_flag='0';
COMMIT;
SET FOREIGN_KEY_CHECKS = @OLD_FK;
SELECT 'dept_tree' s, dept_id, parent_id, dept_name, status, del_flag FROM sys_dept WHERE del_flag='0' ORDER BY parent_id, order_num, dept_id;
SELECT 'roles' s, role_id, role_key, role_name, data_scope, status, del_flag FROM sys_role WHERE del_flag='0' ORDER BY role_sort;
SELECT 'posts' s, post_id, post_code, post_name, status FROM sys_post WHERE status='0' ORDER BY post_sort;
SELECT 'users' s, user_id, login_name, user_name, dept_id, status, remark FROM sys_user WHERE del_flag='0' ORDER BY user_id;
